version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: flash-card-backend
    ports:
      - ":8080"
    
    env_file:
      - .env  
    command: "node dist/main.js"
