name: Flash Card API Deployment to Google Cloud Run 
on:
  push:
    branches:
      - develop

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    
      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |-
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker
      - name: Build and Push Docker Image
        run: |-
          # Build the container on Cloud Build
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/flash-card-api

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: '${{ env.SERVICE }}'
          image: 'gcr.io/${{ secrets.GCP_PROJECT_ID }}/flash-card-api'
          region: 'asia-southeast1'
          env_vars: 'NODE_ENV=production \
                    GOOGLE_CLOUD_PROJECT=${{ secrets.GCP_PROJECT_ID }} \
                    GOOGLE_CLOUD_KEYFILE=${{ secrets.GCP_SA_KEY }} \
                    FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} \
                    FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }} \
                    FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }} \
                    FIREBAE_TYPE=${{ secrets.FIREBASE_TYPE }} \
                    FIREBASE_PRIVATE_KEY_ID=${{ secrets.FIREBASE_PRIVATE_KEY_ID }} \
                    FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }} \
                    FIREBASE_CLIENT_ID=${ { secrets.FIREBASE_CLIENT_ID }} \
                    FIREBASE_AUTH_URI=${{ secrets.FIREBASE_AUTH_URI }} \
                    FIREBASE_TOKEN_URI=${{ secrets.FIREBASE_TOKEN_URI }} \
                    FIREBASE_AUTH_PROVIDER_X509_CERT_URL=${{ secrets.FIREBASE_AUTH_PROVIDER_X509_CERT_URL }} \
                    FIREBASE_CLIENT_X509_CERT_URL=${{ secrets.FIREBASE_CLIENT_X509_CERT_URL }} \
                    MONGODB_URI=${{ secrets.MONGODB_URI }}'
          
  
            
                      