name: Flash Card API Deployment to Google Cloud Run 
on:
  push:
    branches:
      - FLASHCARD-4-authentication-api

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
     
      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |-
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker
      - name: Build and Push Docker Image
        run: |-
          # Build the container on Cloud Build
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/flash-card-api

          
      - name: Deploy to Cloud Run
        run: |-
          # Deploy the container to Cloud Run
          gcloud run deploy flash-card-api \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/flash-card-api \
            --platform managed \
            --region asia-southeast1 \
            --allow-unauthenticated \
            --set-env-vars=NODE_ENV=production \
            --set-env-vars=GOOGLE_CLOUD_PROJECT=${{ secrets.GCP_PROJECT_ID }} \
            --set-env-vars=GOOGLE_CLOUD_KEYFILE=${{ secrets.GCP_SA_KEY }} \
            --set-env-vars=FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} \
            --set-env-vars=FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }} \
            --set-env-vars=FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }} \
            --set-env-vars=FIREBAE_TYPE=${{ secrets.FIREBASE_TYPE }} \
            --set-env-vars=FIREBASE_PRIVATE_KEY_ID=${{ secrets.FIREBASE_PRIVATE_KEY_ID }} \
            --set-env-vars=FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }} \
            --set-env-vars=FIREBASE_CLIENT_ID=${ { secrets.FIREBASE_CLIENT_ID }} \
            --set-env-vars=FIREBASE_AUTH_URI=${{ secrets.FIREBASE_AUTH_URI }} \
            --set-env-vars=FIREBASE_TOKEN_URI=${{ secrets.FIREBASE_TOKEN_URI }} \
            --set-env-vars=FIREBASE_AUTH_PROVIDER_X509_CERT_URL=${{ secrets.FIREBASE_AUTH_PROVIDER_X509_CERT_URL }} \
            --set-env-vars=FIREBASE_CLIENT_X509_CERT_URL=${{ secrets.FIREBASE_CLIENT_X509_CERT_URL }} \
            --set-env-vars=MONGODB_URI=${{ secrets.MONGODB_URI }}
            --set-env-vars=PORT=${{ secrets.PORT }}
         
                      